<div
  data-cy="hero-container"
  class="
    flex
    flex-col
    md:flex-row
    lg:max-w-[1110px]
    lg:mx-auto
  "
>
<div
  class="
    flex
    flex-col
    max-w-[90%]
    md:max-w-[50%]
    mx-auto
    md:mx-[30px]
    mt-7
    md:mt-12
    md:flex-1
  "
>
  <div
    class="
      hero-text-section
      md:mt-[50px]
      md:max-w-[400px]
      lg:max-w-[457px]
    "
  >
    <h1
      data-cy="hero-header"
      class="
        text-h2
        lg:text-h1
        text-black
        font-extrabold
      "
    >
      Maximize skill,
    minimize budget
    </h1>
    <p
      data-cy="hero-description"
      class="
        text-body-sm
        text-grey
        font-light
        my-7
      "
    >
      Our modern courses across a range of in-demand skills will give you the knowledge you need to live the life you want.
    </p>
    <button
      data-cy="get-started-button"
      class="
        btn
        btn-pink
        btn-md
      "
    >
      Get Started
    </button>
  </div>
</div>
  <div
    data-cy="hero-image"
    class="
      relative
      overflow-visible
      mt-10
      md:hidden
    "
  >
    <div
      data-cy="hero-image-container"
      class="
        relative
        top-0
        left-0
        hero-image-section
        bg-[url('/assets/image-hero-mobile.png')]
        md:bg-[url('/assets/image-hero-tablet.png')]
        bg-cover
        bg-no-repeat
        h-96
        w-full
        block
      "
    >
    </div>
  </div>
  <div
    class="
      hidden
      md:flex
      lg:hidden
      hero-image-tablet
    "
  >
    <img 
      src="assets/image-hero-tablet.png" 
      alt="Hero"
    >
  </div>
  <div
    class="
      hidden
      lg:flex
      hero-image-desktop
    "
  >
    <img 
      src="assets/image-hero-desktop.png" 
      alt="Hero"
    >
  </div>
</div>
